/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminUserRecord { 'tier' : string, 'principalId' : Principal }
export interface BillingEvent {
  'id' : bigint,
  'userId' : Principal,
  'note' : string,
  'tier' : string,
  'currency' : string,
  'timestamp' : bigint,
  'amount' : number,
  'eventType' : string,
}
export interface ContentSettings {
  'demoModeEnabled' : boolean,
  'announcementBanner' : string,
  'affiliateEnabled' : boolean,
}
export interface DistributeResult {
  'updatedEngines' : Array<Engine>,
  'overallResilienceScore' : bigint,
}
export interface Engine {
  'id' : bigint,
  'cpu' : bigint,
  'ram' : bigint,
  'status' : string,
  'costPerHour' : number,
  'provider' : string,
  'ownerId' : Principal,
  'storage' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'resilienceScore' : bigint,
}
export interface FlaggedAffiliate {
  'id' : bigint,
  'principal' : string,
  'code' : string,
  'flaggedAt' : bigint,
  'reason' : string,
}
export interface MigrationRecord {
  'id' : bigint,
  'status' : string,
  'engineId' : bigint,
  'savedPerMonth' : number,
  'appCount' : bigint,
  'toProvider' : string,
  'timestamp' : bigint,
  'fromProvider' : string,
  'engineName' : string,
}
export interface SeatMember {
  'role' : string,
  'invitedAt' : bigint,
  'principalId' : Principal,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WaitlistEntry {
  'id' : bigint,
  'name' : string,
  'submittedAt' : bigint,
  'email' : string,
}
export interface _SERVICE {
  '_getMigrationHistoryForTests' : ActorMethod<[], Array<MigrationRecord>>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimInitialAdmin' : ActorMethod<[], boolean>,
  'clearFlaggedAffiliate' : ActorMethod<[string], boolean>,
  'createEngine' : ActorMethod<
    [string, string, bigint, bigint, bigint, number],
    bigint
  >,
  'deleteEngine' : ActorMethod<[bigint], undefined>,
  'deployApp' : ActorMethod<[bigint, string], string>,
  'distributeAcrossProviders' : ActorMethod<[], undefined>,
  'distributeAndGetScore' : ActorMethod<[], DistributeResult>,
  'getAdminAnalytics' : ActorMethod<
    [],
    {
      'freeCount' : bigint,
      'businessCount' : bigint,
      'totalWaitlist' : bigint,
      'totalEngines' : bigint,
      'totalUsers' : bigint,
      'proCount' : bigint,
      'enterpriseCount' : bigint,
    }
  >,
  'getBillingEvents' : ActorMethod<[], Array<BillingEvent>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContentSettings' : ActorMethod<[], ContentSettings>,
  'getCostSummary' : ActorMethod<
    [],
    { 'totalCost' : number, 'engineCosts' : Array<[bigint, number]> }
  >,
  'getEngine' : ActorMethod<[bigint], Engine>,
  'getFlaggedAffiliates' : ActorMethod<[], Array<FlaggedAffiliate>>,
  'getMigrationHistory' : ActorMethod<[], Array<MigrationRecord>>,
  'getMySubscription' : ActorMethod<[], string>,
  'getPublicContentSettings' : ActorMethod<[], ContentSettings>,
  'getReferralCount' : ActorMethod<[string], bigint>,
  'getUsageSummary' : ActorMethod<
    [],
    {
      'enginesCount' : bigint,
      'deploymentsThisMonth' : bigint,
      'migrationsThisMonth' : bigint,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWaitlistEntries' : ActorMethod<[], Array<WaitlistEntry>>,
  'inviteSeat' : ActorMethod<[Principal, string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinWaitlist' : ActorMethod<[string, string], boolean>,
  'listAllUsers' : ActorMethod<[], Array<AdminUserRecord>>,
  'listEngines' : ActorMethod<[], Array<Engine>>,
  'listSeats' : ActorMethod<[], Array<SeatMember>>,
  'migrateEngine' : ActorMethod<[bigint, string], undefined>,
  'migrateEngineWithDetails' : ActorMethod<[bigint, string], MigrationRecord>,
  'populateDemoData' : ActorMethod<[], undefined>,
  'removeSeat' : ActorMethod<[Principal], undefined>,
  'reportReferral' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'capReached' : null } |
      { 'flagged' : null }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveContentSettings' : ActorMethod<[ContentSettings], undefined>,
  'sendMessage' : ActorMethod<[string, [] | [bigint]], string>,
  'setUserTier' : ActorMethod<[Principal, string], undefined>,
  'updateEngineStatus' : ActorMethod<[bigint, string], undefined>,
  'upgradeSubscription' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];