/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MigrationRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'engineId' : IDL.Nat,
  'savedPerMonth' : IDL.Float64,
  'appCount' : IDL.Nat,
  'toProvider' : IDL.Text,
  'timestamp' : IDL.Int,
  'fromProvider' : IDL.Text,
  'engineName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Engine = IDL.Record({
  'id' : IDL.Nat,
  'cpu' : IDL.Nat,
  'ram' : IDL.Nat,
  'status' : IDL.Text,
  'costPerHour' : IDL.Float64,
  'provider' : IDL.Text,
  'ownerId' : IDL.Principal,
  'storage' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'resilienceScore' : IDL.Nat,
});
export const DistributeResult = IDL.Record({
  'updatedEngines' : IDL.Vec(Engine),
  'overallResilienceScore' : IDL.Nat,
});
export const BillingEvent = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'note' : IDL.Text,
  'tier' : IDL.Text,
  'currency' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Float64,
  'eventType' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SeatMember = IDL.Record({
  'role' : IDL.Text,
  'invitedAt' : IDL.Int,
  'principalId' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_getMigrationHistoryForTests' : IDL.Func(
      [],
      [IDL.Vec(MigrationRecord)],
      ['query'],
    ),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEngine' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'deleteEngine' : IDL.Func([IDL.Nat], [], []),
  'deployApp' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
  'distributeAcrossProviders' : IDL.Func([], [], []),
  'distributeAndGetScore' : IDL.Func([], [DistributeResult], []),
  'getBillingEvents' : IDL.Func([], [IDL.Vec(BillingEvent)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCostSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalCost' : IDL.Float64,
          'engineCosts' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Float64)),
        }),
      ],
      ['query'],
    ),
  'getEngine' : IDL.Func([IDL.Nat], [Engine], ['query']),
  'getMigrationHistory' : IDL.Func([], [IDL.Vec(MigrationRecord)], ['query']),
  'getMySubscription' : IDL.Func([], [IDL.Text], ['query']),
  'getUsageSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'enginesCount' : IDL.Nat,
          'deploymentsThisMonth' : IDL.Nat,
          'migrationsThisMonth' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'inviteSeat' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listEngines' : IDL.Func([], [IDL.Vec(Engine)], ['query']),
  'listSeats' : IDL.Func([], [IDL.Vec(SeatMember)], ['query']),
  'migrateEngine' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'migrateEngineWithDetails' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [MigrationRecord],
      [],
    ),
  'populateDemoData' : IDL.Func([], [], []),
  'removeSeat' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Opt(IDL.Nat)], [IDL.Text], []),
  'updateEngineStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'upgradeSubscription' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MigrationRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'engineId' : IDL.Nat,
    'savedPerMonth' : IDL.Float64,
    'appCount' : IDL.Nat,
    'toProvider' : IDL.Text,
    'timestamp' : IDL.Int,
    'fromProvider' : IDL.Text,
    'engineName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Engine = IDL.Record({
    'id' : IDL.Nat,
    'cpu' : IDL.Nat,
    'ram' : IDL.Nat,
    'status' : IDL.Text,
    'costPerHour' : IDL.Float64,
    'provider' : IDL.Text,
    'ownerId' : IDL.Principal,
    'storage' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'resilienceScore' : IDL.Nat,
  });
  const DistributeResult = IDL.Record({
    'updatedEngines' : IDL.Vec(Engine),
    'overallResilienceScore' : IDL.Nat,
  });
  const BillingEvent = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'note' : IDL.Text,
    'tier' : IDL.Text,
    'currency' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Float64,
    'eventType' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SeatMember = IDL.Record({
    'role' : IDL.Text,
    'invitedAt' : IDL.Int,
    'principalId' : IDL.Principal,
  });
  
  return IDL.Service({
    '_getMigrationHistoryForTests' : IDL.Func(
        [],
        [IDL.Vec(MigrationRecord)],
        ['query'],
      ),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEngine' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'deleteEngine' : IDL.Func([IDL.Nat], [], []),
    'deployApp' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
    'distributeAcrossProviders' : IDL.Func([], [], []),
    'distributeAndGetScore' : IDL.Func([], [DistributeResult], []),
    'getBillingEvents' : IDL.Func([], [IDL.Vec(BillingEvent)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCostSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalCost' : IDL.Float64,
            'engineCosts' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Float64)),
          }),
        ],
        ['query'],
      ),
    'getEngine' : IDL.Func([IDL.Nat], [Engine], ['query']),
    'getMigrationHistory' : IDL.Func([], [IDL.Vec(MigrationRecord)], ['query']),
    'getMySubscription' : IDL.Func([], [IDL.Text], ['query']),
    'getUsageSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'enginesCount' : IDL.Nat,
            'deploymentsThisMonth' : IDL.Nat,
            'migrationsThisMonth' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'inviteSeat' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listEngines' : IDL.Func([], [IDL.Vec(Engine)], ['query']),
    'listSeats' : IDL.Func([], [IDL.Vec(SeatMember)], ['query']),
    'migrateEngine' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'migrateEngineWithDetails' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [MigrationRecord],
        [],
      ),
    'populateDemoData' : IDL.Func([], [], []),
    'removeSeat' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Opt(IDL.Nat)], [IDL.Text], []),
    'updateEngineStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'upgradeSubscription' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };