/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BillingEvent {
  'id' : bigint,
  'userId' : Principal,
  'note' : string,
  'tier' : string,
  'currency' : string,
  'timestamp' : bigint,
  'amount' : number,
  'eventType' : string,
}
export interface DistributeResult {
  'updatedEngines' : Array<Engine>,
  'overallResilienceScore' : bigint,
}
export interface Engine {
  'id' : bigint,
  'cpu' : bigint,
  'ram' : bigint,
  'status' : string,
  'costPerHour' : number,
  'provider' : string,
  'ownerId' : Principal,
  'storage' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'resilienceScore' : bigint,
}
export interface MigrationRecord {
  'id' : bigint,
  'status' : string,
  'engineId' : bigint,
  'savedPerMonth' : number,
  'appCount' : bigint,
  'toProvider' : string,
  'timestamp' : bigint,
  'fromProvider' : string,
  'engineName' : string,
}
export interface SeatMember {
  'role' : string,
  'invitedAt' : bigint,
  'principalId' : Principal,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_getMigrationHistoryForTests' : ActorMethod<[], Array<MigrationRecord>>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEngine' : ActorMethod<
    [string, string, bigint, bigint, bigint, number],
    bigint
  >,
  'deleteEngine' : ActorMethod<[bigint], undefined>,
  'deployApp' : ActorMethod<[bigint, string], string>,
  'distributeAcrossProviders' : ActorMethod<[], undefined>,
  /**
   * / * Distributes all caller's engines across providers and computes overall resilience score.
   */
  'distributeAndGetScore' : ActorMethod<[], DistributeResult>,
  'getBillingEvents' : ActorMethod<[], Array<BillingEvent>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCostSummary' : ActorMethod<
    [],
    { 'totalCost' : number, 'engineCosts' : Array<[bigint, number]> }
  >,
  'getEngine' : ActorMethod<[bigint], Engine>,
  /**
   * / * Returns all migration records for the caller, newest first (descending by id).
   */
  'getMigrationHistory' : ActorMethod<[], Array<MigrationRecord>>,
  'getMySubscription' : ActorMethod<[], string>,
  'getUsageSummary' : ActorMethod<
    [],
    {
      'enginesCount' : bigint,
      'deploymentsThisMonth' : bigint,
      'migrationsThisMonth' : bigint,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'inviteSeat' : ActorMethod<[Principal, string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listEngines' : ActorMethod<[], Array<Engine>>,
  'listSeats' : ActorMethod<[], Array<SeatMember>>,
  'migrateEngine' : ActorMethod<[bigint, string], undefined>,
  /**
   * / * Migrates an engine to a new provider and returns the migration record.
   * /   * Computes mock savings and updates the engine state.
   */
  'migrateEngineWithDetails' : ActorMethod<[bigint, string], MigrationRecord>,
  'populateDemoData' : ActorMethod<[], undefined>,
  'removeSeat' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[string, [] | [bigint]], string>,
  'updateEngineStatus' : ActorMethod<[bigint, string], undefined>,
  'upgradeSubscription' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];