/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Engine {
    id: bigint;
    cpu: bigint;
    ram: bigint;
    status: string;
    costPerHour: number;
    provider: string;
    ownerId: Principal;
    storage: bigint;
    name: string;
    createdAt: bigint;
    resilienceScore: bigint;
}
export interface AdminUserRecord {
    tier: string;
    principalId: Principal;
}
export interface WaitlistEntry {
    id: bigint;
    name: string;
    submittedAt: bigint;
    email: string;
}
export interface FlaggedAffiliate {
    id: bigint;
    principal: string;
    code: string;
    flaggedAt: bigint;
    reason: string;
}
export interface DistributeResult {
    updatedEngines: Array<Engine>;
    overallResilienceScore: bigint;
}
export interface SeatMember {
    role: string;
    invitedAt: bigint;
    principalId: Principal;
}
export interface BillingEvent {
    id: bigint;
    userId: Principal;
    note: string;
    tier: string;
    currency: string;
    timestamp: bigint;
    amount: number;
    eventType: string;
}
export interface MigrationRecord {
    id: bigint;
    status: string;
    engineId: bigint;
    savedPerMonth: number;
    appCount: bigint;
    toProvider: string;
    timestamp: bigint;
    fromProvider: string;
    engineName: string;
}
export interface UserProfile {
    name: string;
}
export interface ContentSettings {
    demoModeEnabled: boolean;
    announcementBanner: string;
    affiliateEnabled: boolean;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _getMigrationHistoryForTests(): Promise<Array<MigrationRecord>>;
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    claimInitialAdmin(): Promise<boolean>;
    clearFlaggedAffiliate(code: string): Promise<boolean>;
    createEngine(name: string, provider: string, cpu: bigint, ram: bigint, storage: bigint, costPerHour: number): Promise<bigint>;
    deleteEngine(id: bigint): Promise<void>;
    deleteUserData(user: Principal): Promise<boolean>;
    deployApp(engineId: bigint, _prompt: string): Promise<string>;
    distributeAcrossProviders(): Promise<void>;
    distributeAndGetScore(): Promise<DistributeResult>;
    getAdminAnalytics(): Promise<{
        freeCount: bigint;
        businessCount: bigint;
        totalWaitlist: bigint;
        totalEngines: bigint;
        totalUsers: bigint;
        proCount: bigint;
        enterpriseCount: bigint;
    }>;
    getBillingEvents(): Promise<Array<BillingEvent>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContentSettings(): Promise<ContentSettings>;
    getCostSummary(): Promise<{
        totalCost: number;
        engineCosts: Array<[bigint, number]>;
    }>;
    getEngine(id: bigint): Promise<Engine>;
    getFlaggedAffiliates(): Promise<Array<FlaggedAffiliate>>;
    getMigrationHistory(): Promise<Array<MigrationRecord>>;
    getMySubscription(): Promise<string>;
    getPublicContentSettings(): Promise<ContentSettings>;
    getReferralCount(code: string): Promise<bigint>;
    getUsageSummary(): Promise<{
        enginesCount: bigint;
        deploymentsThisMonth: bigint;
        migrationsThisMonth: bigint;
    }>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWaitlistEntries(): Promise<Array<WaitlistEntry>>;
    inviteSeat(member: Principal, role: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    joinWaitlist(email: string, name: string): Promise<boolean>;
    listAllUsers(): Promise<Array<AdminUserRecord>>;
    listEngines(): Promise<Array<Engine>>;
    listSeats(): Promise<Array<SeatMember>>;
    migrateEngine(id: bigint, targetProvider: string): Promise<void>;
    migrateEngineWithDetails(id: bigint, targetProvider: string): Promise<MigrationRecord>;
    populateDemoData(): Promise<void>;
    removeSeat(member: Principal): Promise<void>;
    reportReferral(code: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "capReached";
        capReached: null;
    } | {
        __kind__: "flagged";
        flagged: null;
    }>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveContentSettings(settings: ContentSettings): Promise<void>;
    sendMessage(content: string, _engineId: bigint | null): Promise<string>;
    setUserTier(user: Principal, tier: string): Promise<void>;
    updateEngineStatus(id: bigint, status: string): Promise<void>;
    upgradeSubscription(tier: string, paymentMethod: string): Promise<void>;
}
import type { UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _getMigrationHistoryForTests(): Promise<Array<MigrationRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor._getMigrationHistoryForTests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._getMigrationHistoryForTests();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async claimInitialAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimInitialAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimInitialAdmin();
            return result;
        }
    }
    async clearFlaggedAffiliate(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.clearFlaggedAffiliate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearFlaggedAffiliate(arg0);
            return result;
        }
    }
    async createEngine(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: bigint, arg5: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEngine(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEngine(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async deleteEngine(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEngine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEngine(arg0);
            return result;
        }
    }
    async deleteUserData(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUserData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUserData(arg0);
            return result;
        }
    }
    async deployApp(arg0: bigint, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.deployApp(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deployApp(arg0, arg1);
            return result;
        }
    }
    async distributeAcrossProviders(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.distributeAcrossProviders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.distributeAcrossProviders();
            return result;
        }
    }
    async distributeAndGetScore(): Promise<DistributeResult> {
        if (this.processError) {
            try {
                const result = await this.actor.distributeAndGetScore();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.distributeAndGetScore();
            return result;
        }
    }
    async getAdminAnalytics(): Promise<{
        freeCount: bigint;
        businessCount: bigint;
        totalWaitlist: bigint;
        totalEngines: bigint;
        totalUsers: bigint;
        proCount: bigint;
        enterpriseCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminAnalytics();
            return result;
        }
    }
    async getBillingEvents(): Promise<Array<BillingEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBillingEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBillingEvents();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContentSettings(): Promise<ContentSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getContentSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContentSettings();
            return result;
        }
    }
    async getCostSummary(): Promise<{
        totalCost: number;
        engineCosts: Array<[bigint, number]>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCostSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCostSummary();
            return result;
        }
    }
    async getEngine(arg0: bigint): Promise<Engine> {
        if (this.processError) {
            try {
                const result = await this.actor.getEngine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEngine(arg0);
            return result;
        }
    }
    async getFlaggedAffiliates(): Promise<Array<FlaggedAffiliate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlaggedAffiliates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlaggedAffiliates();
            return result;
        }
    }
    async getMigrationHistory(): Promise<Array<MigrationRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMigrationHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMigrationHistory();
            return result;
        }
    }
    async getMySubscription(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySubscription();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySubscription();
            return result;
        }
    }
    async getPublicContentSettings(): Promise<ContentSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicContentSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicContentSettings();
            return result;
        }
    }
    async getReferralCount(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralCount(arg0);
            return result;
        }
    }
    async getUsageSummary(): Promise<{
        enginesCount: bigint;
        deploymentsThisMonth: bigint;
        migrationsThisMonth: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsageSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsageSummary();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWaitlistEntries(): Promise<Array<WaitlistEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWaitlistEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWaitlistEntries();
            return result;
        }
    }
    async inviteSeat(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.inviteSeat(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.inviteSeat(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinWaitlist(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.joinWaitlist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinWaitlist(arg0, arg1);
            return result;
        }
    }
    async listAllUsers(): Promise<Array<AdminUserRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsers();
            return result;
        }
    }
    async listEngines(): Promise<Array<Engine>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEngines();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEngines();
            return result;
        }
    }
    async listSeats(): Promise<Array<SeatMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSeats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSeats();
            return result;
        }
    }
    async migrateEngine(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.migrateEngine(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.migrateEngine(arg0, arg1);
            return result;
        }
    }
    async migrateEngineWithDetails(arg0: bigint, arg1: string): Promise<MigrationRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.migrateEngineWithDetails(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.migrateEngineWithDetails(arg0, arg1);
            return result;
        }
    }
    async populateDemoData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.populateDemoData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.populateDemoData();
            return result;
        }
    }
    async removeSeat(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeSeat(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeSeat(arg0);
            return result;
        }
    }
    async reportReferral(arg0: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "capReached";
        capReached: null;
    } | {
        __kind__: "flagged";
        flagged: null;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.reportReferral(arg0);
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportReferral(arg0);
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveContentSettings(arg0: ContentSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveContentSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveContentSettings(arg0);
            return result;
        }
    }
    async sendMessage(arg0: string, arg1: bigint | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setUserTier(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserTier(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserTier(arg0, arg1);
            return result;
        }
    }
    async updateEngineStatus(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEngineStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEngineStatus(arg0, arg1);
            return result;
        }
    }
    async upgradeSubscription(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upgradeSubscription(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upgradeSubscription(arg0, arg1);
            return result;
        }
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    capReached: null;
} | {
    flagged: null;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "capReached";
    capReached: null;
} | {
    __kind__: "flagged";
    flagged: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "capReached" in value ? {
        __kind__: "capReached",
        capReached: value.capReached
    } : "flagged" in value ? {
        __kind__: "flagged",
        flagged: value.flagged
    } : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
